steps:
  - id: "branch name"
    name: "alpine"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        echo "***************************************"
        echo "$BRANCH_NAME"
        echo "***************************************"

  - id: 'tf init'
    name: 'hashicorp/terraform:6.6.0'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
          terraform init

  - id: 'tf-plan'
    name: 'hashicorp/terraform:6.6.0'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
          terraform plan

  - id: 'tf apply'
    name: 'hashicorp/terraform:6.6.0'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
          if [[ "$BRANCH_NAME" == "prod" ]]; then
            echo "Branch is 'prod', proceeding with terraform apply."
            terraform apply --auto-approve
            exit 0
          else
            echo "Branch is not 'prod', skipping terraform apply."
            exit 0
          fi

# Choose one of the following logging options based on your needs:

# # Option 1: Specify a logs bucket
# logsBucket: 'gs://your-log-bucket-name'

# # Option 2: Use regional user-owned bucket behavior
# options:
#   defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET

# # Option 3: Use Cloud Logging only
options:
  logging: CLOUD_LOGGING_ONLY